/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.featuregroupmapping;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FeatureGroupMappingRuntimeModule extends org.osate.xtext.aadl2.featuregroupmapping.AbstractFeatureGroupMappingRuntimeModule {

	@Override
	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return org.osate.xtext.aadl2.featuregroupmapping.naming.FeatureGroupMappingQualifiedNameProvider.class;
	}
}
