/*
* generated by Xtext
*/
package org.osate.xtext.aadl2.featuregroupmapping.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class FeatureGroupMappingOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
