/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.featuregroupmapping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class FeatureGroupMappingUiModule extends org.osate.xtext.aadl2.featuregroupmapping.ui.AbstractFeatureGroupMappingUiModule {
	public FeatureGroupMappingUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
