/*
* generated by Xtext
*/
package org.osate.xtext.aadl2.featuregroupmapping.ui.contentassist;

import org.osate.xtext.aadl2.featuregroupmapping.ui.contentassist.AbstractFeatureGroupMappingProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class FeatureGroupMappingProposalProvider extends AbstractFeatureGroupMappingProposalProvider {

}
