/*
 * generated by Xtext
 */
package org.osate.xtext.aadl2.featuregroupmapping.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.osate.xtext.aadl2.featuregroupmapping.ui.internal.FeatureGroupMappingActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FeatureGroupMappingExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FeatureGroupMappingActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return FeatureGroupMappingActivator.getInstance().getInjector(FeatureGroupMappingActivator.ORG_OSATE_XTEXT_AADL2_FEATUREGROUPMAPPING_FEATUREGROUPMAPPING);
	}
	
}
